web:
  image: nginx
  volumes:
   - ./frontend/public:/data
   - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
   - "8888:80"
  environment:
   - NGINX_HOST=nginx.local
   - NGINX_PORT=80
  # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"